### ISSUE TITLE
Facebook not pulling right events

### ISSUE THREAD

**Issue by jsdavis** [ucsdcses/server#16]
Should be seeing these events:
![image](https://cloud.githubusercontent.com/assets/9905972/24441332/ff41c12a-140d-11e7-9e6e-99a5df12b8c8.png)

Instead we're getting events hosted last year by people other than the CSES UCSD page

**Comment by jsdavis** [comment]
Also, every event on the page says 12:00AM

**Comment by maxwell-bland** [comment]
Ah, these are the events off of the page; I had been grabbing events off the group! Is this a bug or a "feature"? Anyways, I'll make it grab from the page instead.
![screenshot from 2017-03-29 11 44 41](https://cloud.githubusercontent.com/assets/13628519/24470897/4fb1b45a-1475-11e7-8b73-d8677650b36a.jpeg)

**Comment by maxwell-bland** [comment]
That 12am thing should not be happening however, I'll get on it.

**Comment by maxwell-bland** [comment]
Most recent commit has fixed this.

**Comment by maxwell-bland** [comment]
Additionally, make sure to clean your cache, or changes won't show up.
