### ISSUE TITLE
Events not showing up

### ISSUE THREAD

**Issue by jsdavis** [ucsdcses/server#21]
![image](https://cloud.githubusercontent.com/assets/9905972/24591815/0093c9e2-17bf-11e7-8ede-23e37269df67.png)

![image](https://cloud.githubusercontent.com/assets/9905972/24591818/0d0126d4-17bf-11e7-86ea-bd4d328df7d0.png)

**Comment by maxwell-bland** [comment]
Fixed, .env had a bad api key. Going to address the other issues in this coming week.
